/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bpjs;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.xml.transform.Result;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DaffaRadhitya
 */
public class formPasien1 extends javax.swing.JFrame {
    DefaultTableModel table1;
    Object[]list_pasien = new Object[9];
    int X = 0;
    Koneksi con = new Koneksi();
    Connection kon = con.getConnection();

    /**
     * Creates new form formPasien1
     */
    public formPasien1() throws SQLException {
        initComponents();
        table1 = new DefaultTableModel();
        jTable.setModel(table1);
        
        table1.addColumn("No");table1.addColumn("RM");
        table1.addColumn("Nama");table1.addColumn("Umur");table1.addColumn("Status Umur");
        table1.addColumn("tinggi (m)");table1.addColumn("berat (kg)");
        table1.addColumn("BMI");
        table1.addColumn("Status Sehat");
        
        
        setResizable(false);
        
        nama1.setEditable(false);rm1.setEditable(false);umur1.setEditable(false);tinggi1.setEditable(false);berat1.setEditable(false);
        proses1.setEnabled(false);
        update.setEnabled(false);
        hapus.setEnabled(false);
        simpan.setEnabled(false);
        
        Tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rm = new javax.swing.JTextField();
        umur = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        berat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        proses = new javax.swing.JToggleButton();
        simpan = new javax.swing.JToggleButton();
        reset = new javax.swing.JToggleButton();
        hapus = new javax.swing.JToggleButton();
        proses1 = new javax.swing.JToggleButton();
        keluar = new javax.swing.JToggleButton();
        cetak = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        nama1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rm1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        umur1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        berat1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bmi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sUmur = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tinggi1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        update = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Nama Pasien :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("No RM         :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Umur             :");

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Tinggi (m)     :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Berat (kg)       :");

        rm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmActionPerformed(evt);
            }
        });

        umur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umurActionPerformed(evt);
            }
        });

        tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiActionPerformed(evt);
            }
        });

        berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Welcome !");

        proses.setBackground(new java.awt.Color(255, 255, 255));
        proses.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        proses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icondangambar/process.png"))); // NOI18N
        proses.setText("Proses");
        proses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetMouseEntered(evt);
            }
        });
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });

        simpan.setBackground(new java.awt.Color(255, 255, 255));
        simpan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icondangambar/diskette_1.png"))); // NOI18N
        simpan.setText("Simpan");
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetMouseEntered(evt);
            }
        });
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(255, 255, 255));
        reset.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icondangambar/refresh.png"))); // NOI18N
        reset.setText("Reset");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetMouseEntered(evt);
            }
        });
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(255, 255, 255));
        hapus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icondangambar/delete.png"))); // NOI18N
        hapus.setText("Hapus");
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetMouseEntered(evt);
            }
        });
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        proses1.setBackground(new java.awt.Color(255, 255, 255));
        proses1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        proses1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icondangambar/process.png"))); // NOI18N
        proses1.setText("Proses");
        proses1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetMouseEntered(evt);
            }
        });
        proses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proses1ActionPerformed(evt);
            }
        });

        keluar.setBackground(new java.awt.Color(255, 255, 255));
        keluar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icondangambar/sign-out.png"))); // NOI18N
        keluar.setSelected(true);
        keluar.setText("Exit");
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetMouseEntered(evt);
            }
        });
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        cetak.setBackground(new java.awt.Color(255, 255, 255));
        cetak.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icondangambar/icons8-print-18.png"))); // NOI18N
        cetak.setSelected(true);
        cetak.setText("Print");
        cetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cetakresetMouseEntered(evt);
            }
        });
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nama, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(rm)
                                    .addComponent(umur)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(tinggi))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(berat)))))
                        .addGap(38, 38, 38))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(proses)
                        .addGap(18, 18, 18)
                        .addComponent(simpan)
                        .addGap(18, 18, 18)
                        .addComponent(reset)))
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(keluar)
                    .addComponent(proses1))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hapus)
                    .addComponent(cetak))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rm, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(umur, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(berat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proses)
                    .addComponent(simpan)
                    .addComponent(reset))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapus)
                    .addComponent(proses1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keluar)
                    .addComponent(cetak))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 492));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("Nama Pasien :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        nama1.setBackground(new java.awt.Color(204, 204, 204));
        nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama1ActionPerformed(evt);
            }
        });
        getContentPane().add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 93, 191, 27));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setText("No RM         :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 131, -1, -1));

        rm1.setEditable(false);
        rm1.setBackground(new java.awt.Color(204, 204, 204));
        rm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rm1ActionPerformed(evt);
            }
        });
        getContentPane().add(rm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 131, 188, 27));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 0));
        jLabel9.setText("Umur            :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 164, -1, -1));

        umur1.setBackground(new java.awt.Color(204, 204, 204));
        umur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umur1ActionPerformed(evt);
            }
        });
        getContentPane().add(umur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 164, 186, 27));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 0));
        jLabel10.setText("Berat            :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 275, -1, -1));

        berat1.setBackground(new java.awt.Color(204, 204, 204));
        berat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berat1ActionPerformed(evt);
            }
        });
        getContentPane().add(berat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 275, 191, 27));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 0));
        jLabel11.setText("BMI             :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 313, -1, -1));

        bmi.setEditable(false);
        bmi.setBackground(new java.awt.Color(204, 204, 204));
        bmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmiActionPerformed(evt);
            }
        });
        getContentPane().add(bmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 313, 191, 27));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 0));
        jLabel12.setText("Status Umur  :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 199, -1, -1));

        sUmur.setEditable(false);
        sUmur.setBackground(new java.awt.Color(204, 204, 204));
        sUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sUmurActionPerformed(evt);
            }
        });
        getContentPane().add(sUmur, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 199, 185, 27));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 0));
        jLabel13.setText("Tinggi           :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 237, -1, -1));

        tinggi1.setBackground(new java.awt.Color(204, 204, 204));
        tinggi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggi1ActionPerformed(evt);
            }
        });
        getContentPane().add(tinggi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 237, 185, 27));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 0));
        jLabel14.setText("Status Kes.    : ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 346, -1, -1));

        status.setEditable(false);
        status.setBackground(new java.awt.Color(204, 204, 204));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 346, 191, 27));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 51, 608, 382));

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icondangambar/icons8-hand-with-pen-64.png"))); // NOI18N
        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetMouseEntered(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Data Pasien");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 11, 150, 34));

        jLabel17.setForeground(new java.awt.Color(204, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icondangambar/12.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 990, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void rmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmActionPerformed

    private void umurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_umurActionPerformed

    private void tinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiActionPerformed

    private void beratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beratActionPerformed

    private void nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama1ActionPerformed

    private void rm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rm1ActionPerformed

    private void umur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_umur1ActionPerformed

    private void berat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_berat1ActionPerformed

    private void bmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bmiActionPerformed

    private void sUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sUmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sUmurActionPerformed

    private void tinggi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggi1ActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String upadtequer = null;
        PreparedStatement ps = null;
       
        upadtequer= "UPDATE `pasien` SET rm=?,nama=?,umur=?,sUmur=?,tinggi=?,`berat`=?,`BMI`= ?,status= ? WHERE rm= ? ";
        try {
            ps = kon.prepareStatement(upadtequer);
            ps.setString(1, rm1.getText());
            ps.setString(2, nama1.getText());
            ps.setString(3, umur1.getText());
            ps.setString(4, sUmur.getText());
            ps.setString(5, tinggi1.getText());
            ps.setString(6, berat1.getText());
            ps.setString(7, bmi.getText());
            ps.setString(8, status.getText());
            ps.setString(9, rm1.getText());
            JOptionPane.showMessageDialog(null, "Data terupdate");
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(formPasien1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Data gak terupdate");
        }
        Reset();
        Refresh();
        try {
            Tampilkan();
        } catch (SQLException ex) {
            Logger.getLogger(formPasien1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_updateActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        Reset();
        proses1.setEnabled(false);
        update.setEnabled(false);
        hapus.setEnabled(false);
        proses.setEnabled(true);
        
    }//GEN-LAST:event_resetActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        Proses();
    }//GEN-LAST:event_prosesActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        PreparedStatement ps;
        try {
            ps = kon.prepareStatement("INSERT INTO `pasien`(`rm`, `nama`, `umur`, `sUmur`, `tinggi`, `berat`, `BMI`, `status`) VALUES (?,?,?,?,?,?,?,?)");
            ps.setString(1, rm1.getText());
            ps.setString(2, nama1.getText());
            ps.setString(3, umur1.getText());
            ps.setString(4, sUmur.getText());
            ps.setString(5, tinggi1.getText());
            ps.setString(6, berat1.getText());
            ps.setString(7, bmi.getText());
            ps.setString(8, status.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
        } catch (SQLException ex) {
            Logger.getLogger(formPasien1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Data Gak Tersimpan");
        }
        Reset();
        Refresh();
        try {
            Tampilkan();
        } catch (SQLException ex) {
            Logger.getLogger(formPasien1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        int index = jTable.getSelectedRow();
        try {
            Terpilih(index);
        } catch (SQLException ex) {
            Logger.getLogger(formPasien1.class.getName()).log(Level.SEVERE, null, ex);
        }
        proses1.setEnabled(true);
        hapus.setEnabled(true);
    }//GEN-LAST:event_jTableMouseClicked

    private void proses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proses1ActionPerformed
        Proses();
        simpan.setEnabled(false);
        update.setEnabled(true);
    }//GEN-LAST:event_proses1ActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        PreparedStatement ps;
        try {
            ps = kon.prepareStatement("DELETE FROM `pasien` WHERE rm =?");
            ps.setString(1, rm.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Terhapus");
        } catch (SQLException ex) {
            Logger.getLogger(formPasien1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Data Gak Terhapus");
        }
        Reset();
        Refresh();
        try {
            Tampilkan();
        } catch (SQLException ex) {
            Logger.getLogger(formPasien1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void resetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_resetMouseEntered

    private void cetakresetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetakresetMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cetakresetMouseEntered

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        JasperReport jp;
        String path =".\\src\\Bpjs\\reportPasien.jasper";
        try {
            jp = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jpr = JasperFillManager.fillReport(path, null,kon);
            JasperViewer jv = new JasperViewer(jpr,false);
            jv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jv.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(formPasien1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cetakActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPasien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPasien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPasien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPasien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new formPasien1().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(formPasien1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField berat;
    private javax.swing.JTextField berat1;
    private javax.swing.JTextField bmi;
    private javax.swing.JToggleButton cetak;
    private javax.swing.JToggleButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JToggleButton keluar;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nama1;
    private javax.swing.JToggleButton proses;
    private javax.swing.JToggleButton proses1;
    private javax.swing.JToggleButton reset;
    private javax.swing.JTextField rm;
    private javax.swing.JTextField rm1;
    private javax.swing.JTextField sUmur;
    private javax.swing.JToggleButton simpan;
    private javax.swing.JTextField status;
    private javax.swing.JTextField tinggi;
    private javax.swing.JTextField tinggi1;
    private javax.swing.JTextField umur;
    private javax.swing.JTextField umur1;
    private javax.swing.JToggleButton update;
    // End of variables declaration//GEN-END:variables
public void Tampilkan() throws SQLException {
        ArrayList[] list = getPasList();
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        Object[]row = new Object[9];
        for(int i = 0;i<list.length;i++){
            row[0]=i+1;
            row[1]=list[i].get(0);
            row[2]=list[i].get(1);
            row[3]=list[i].get(2);
            row[4]=list[i].get(3);
            row[5]=list[i].get(4);
            row[6]=list[i].get(5);
            row[7]=list[i].get(6);
            row[8]=list[i].get(7);
            
            model.addRow(row);
        }
    }
 public void Reset(){
        nama.setText("");rm.setText("");
        umur.setText("");umur1.setText("");
        sUmur.setText("");
        tinggi.setText("");tinggi1.setText("");
        berat.setText("");berat1.setText("");
        bmi.setText("");status.setText("");
        nama1.setText("");rm1.setText("");
    }
public ArrayList[] getPasList() throws SQLException {
       String query = "SELECT COUNT(*) AS c FROM pasien";
        Statement st;
        Result set;
        ResultSet resCount, rs;
        st =  kon.createStatement();
        resCount = st.executeQuery(query);
        int size = 0;
        while(resCount.next()){
            size = resCount.getInt("c");
        }
        ArrayList[]paslist = new ArrayList[size];
        String queryne = "SELECT * FROM pasien";
        rs = st.executeQuery(queryne);
        int x = 0;
        while(rs.next()){
            paslist[x] = new ArrayList<>();
            paslist[x].add(rs.getString("rm"));
            paslist[x].add(rs.getString("nama"));
            paslist[x].add(rs.getString("umur"));
            paslist[x].add(rs.getString("sUmur"));
            paslist[x].add(rs.getString("tinggi"));
            paslist[x].add(rs.getString("berat"));
            paslist[x].add(rs.getString("BMI"));
            paslist[x].add(rs.getString("status"));
            x++;
            
        
        }
        return paslist;
    }
public void Proses(){
        try{
            String nama = this.nama.getText();
            String rm = this.rm.getText();
            String tinggine = tinggi.getText().toString();
            String berate = berat.getText().toString();
            Double tinggi = Double.parseDouble(this.tinggi.getText());
            Double berat = Double.parseDouble(this.berat.getText());
            String umurstr = umur.getText().toString();
            Integer umur = Integer.parseInt(umurstr);

            Pasien pas = new Pasien(rm, nama, tinggi, berat, umur);
            nama1.setText(nama);rm1.setText(rm);umur1.setText(umurstr);
            sUmur.setText(pas.getSumur(umur));
            tinggi1.setText(tinggine);berat1.setText(berate);
            bmi.setText(""+pas.BMI());
            status.setText(pas.getStatus(pas.BMI()));
            simpan.setEnabled(true);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Inputan kosong", "Warning",JOptionPane.WARNING_MESSAGE);
        }
    }
public  void Refresh(){
        DefaultTableModel model = (DefaultTableModel)this.jTable.getModel();
        model.setRowCount(0);
    }

    private void Terpilih(int index) throws SQLException {
        ArrayList[] list = getPasList();
        rm.setText((String)list[index].get(0));
        nama.setText((String)list[index].get(1));
        umur.setText((String)list[index].get(2).toString());
        tinggi.setText((String)list[index].get(4).toString());
        berat.setText((String)list[index].get(5).toString());        
        proses.setEnabled(false);
        simpan.setEnabled(false);
    }
}

